

export const SAVE_CREATED_ACCOUNT = 'SAVE_CREATED_ACCOUNT';
export type SAVE_CREATED_ACCOUNT = typeof SAVE_CREATED_ACCOUNT;

export const ACCOUNT_CREATION_FAILED = 'ACCOUNT_CREATION_FAILED';
export type ACCOUNT_CREATION_FAILED = typeof ACCOUNT_CREATION_FAILED;

export const PLAID_ERROR = 'PLAID_ERROR';
export type PLAID_ERROR = typeof PLAID_ERROR;

export const SAVE_RATES = 'SAVE_RATES';
export type SAVE_RATES = typeof SAVE_RATES;

export const SAVE_LIMITS = 'SAVE_LIMITS';
export type SAVE_LIMITS = 'SAVE_LIMITS'

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export type SAVE_PAYMENT_METHOD = typeof SAVE_PAYMENT_METHOD;

export const ACCOUNT_FROM_DB = 'ACCOUNT_FROM_DB';
export type ACCOUNT_FROM_DB = typeof ACCOUNT_FROM_DB;

export const SET_PROCESS = 'SET_PROCESS';
export type SET_PROCESS = typeof SET_PROCESS;

export const SAVE_BLOCK_CHAIN = 'SAVE_BLOCK_CHAIN';
export type SAVE_BLOCK_CHAIN = typeof SAVE_BLOCK_CHAIN;

export const BUY_TRANSACTION = 'BUY_TRANSACTION';
export type BUY_TRANSACTION = typeof BUY_TRANSACTION;


export const BUY_TRANSACTION_ERROR = 'BUY_TRANSACTION_ERROR';
export type BUY_TRANSACTION_ERROR = typeof BUY_TRANSACTION_ERROR;

export const SELL_TRANSACTION = 'SELL_TRANSACTION';
export type SELL_TRANSACTION = typeof SELL_TRANSACTION;

export const SELL_TRANSACTION_ERROR = 'SELL_TRANSACTION_ERROR';
export type SELL_TRANSACTION_ERROR = typeof SELL_TRANSACTION_ERROR;

export const START_ACTION = 'START_ACTION';
export type START_ACTION = typeof START_ACTION;

export const SAVE_UNIFYRE_USER_PROFILE = 'SAVE_UNIFYRE_USER_PROFILE';
export type SAVE_UNIFYRE_USER_PROFILE = typeof SAVE_UNIFYRE_USER_PROFILE;

export const SAVE_TRANSFER_QUOTE = 'SAVE_TRANSFER_QUOTE';
export type SAVE_TRANSFER_QUOTE = typeof SAVE_TRANSFER_QUOTE;
