import { type } from "os";

export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SAVE_CREATED_ACCOUNT = 'SAVE_CREATED_ACCOUNT';
export type SAVE_CREATED_ACCOUNT = typeof SAVE_CREATED_ACCOUNT;